- name: Install dnsmasq package
  apt:
    name: dnsmasq
    state: present

- name: Configure dnsmasq
  template:
    src: templates/dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart dnsmasq

- name: Start dnsmasq service
  service:
    name: dnsmasq
    state: started
    enabled: true

handlers:
  - name: restart dnsmasq
    service:
      name: dnsmasq
      state: restarted